name: Release
on:
  push:
  workflow_dispatch:

concurrency:
  group: MSVC
  cancel-in-progress: true

jobs:
  job:
    name: My Job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Download MSVC
        shell: cmd
        run: MSVC-Portable.bat
        
      - name: Pack MSVC to zip
        run: powershell Compress-Archive -Path MSVC\* -DestinationPath MSVC.zip

      - name: Pack MSVC to 7z
        run: |
          choco install 7zip.commandline -y
          7z a MSVC.7z MSVC\*

      - name: Upload MSVC archives as release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            MSVC.zip
            MSVC.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}